version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: aashu-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - aashu-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aashu-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongo:27017/aashu?authSource=admin
      - JWT_SECRET=aashu_secret_key
      - JWT_EXPIRE=30d
    networks:
      - aashu-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aashu-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - aashu-network

networks:
  aashu-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
